name: Doxygen GitHub Pages Deploy Action

on:
  workflow_dispatch: # Changed to trigger only manually

permissions:
  contents: write # REQUIRED: Allows the bot to push to your repository

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        with:
          submodules: "true"
      
      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz doxygen
      
      - name: Generate Doxygen documentation
        run: |
          doxygen Doxyfile

      - name: Create .nojekyll
        run: touch docs/html/.nojekyll
      
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/html # Fixed: Removed 'deploy' from the folder path
